version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: playlist-db
    environment:
      POSTGRES_DB: playlist_migrate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
