spring:
  application:
    name: playlist_migrate

  datasource:
    url: jdbc:postgresql://localhost:5432/playlist_migrate
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
