spring:
  application:
    name: main
  datasource:
    url: jdbc:postgresql://localhost:5432/playlist_migrate
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: |
      %d{dd-MM-yy HH:mm:ss} %highlight(%-5level) %logger.%M - %msg
